from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    # path('', auth_views.LoginView.as_view(template_name='chub/login.html'), name='login'),
    path('',views.index,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.user_logout,name='logout'),
    path('guidelines',views.guide,name='guide'),
    path('dsafasgadfdkh',views.q1,name='1'),
    path('dsfsafsfsdf',views.q2,name='2'),
    path('jhgkhjkhjkgh',views.q3,name='3'),
    path('dghgjkjfsdf',views.q4,name='4'),
    path('tuituohgjkjfsdf',views.q5,name='5'),
    path('dgwrqjkjfsdf',views.q6,name='6'),
    path('dsfbqrh242af',views.q7,name='7'),
    path('dqteqtehu24y134',views.q8,name='8'),
    path('dsfsarwqep214',views.q9,name='9'),
    path('ljkkjlfsdf',views.q10,name='10'),
    path('wieorrfqqwe',views.q11,name='11'),
    path('dsffqw1adf',views.q12,name='12'),
    path('oiijpkijkhn',views.q13,name='13'),
    path('fasdfrwqt',views.q14,name='14'),
    path('baasdgwwuiowt8',views.q15,name='15'),
    path('looppokjkhkk',views.q16,name='16'),
    path('kgjqawlwgwau',views.q17,name='17'),
    path('djodsgads',views.q18,name='18'),
    path('asdglkjsl',views.q19,name='19'),
    path('dgladhg',views.q20,name='20'),
    path('agkulahdsoil',views.q21,name='21'),
    path('gqwoledaslj',views.q22,name='22'),
    path('sdsglkja',views.q23,name='23'),
    path('sdgkjhads',views.q24,name='24'),
    path('end',views.end,name='end'),
]